---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: common

- hosts: k3s-master
  become: yes
  roles:
    - role: master

- hosts: k3s-nodes
  become: yes
  roles:
    - role: nodes